var classes = [
    {
        "name": "FastForward\\Framework\\ServiceProvider\\FrameworkServiceProvider",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FastForward\\Container\\ServiceProvider\\AggregateServiceProvider",
            "FastForward\\Http\\ServiceProvider\\HttpServiceProvider",
            "FastForward\\EventDispatcher\\ServiceProvider\\EventDispatcherServiceProvider",
            "FastForward\\Clock\\ServiceProvider\\ClockServiceProvider"
        ],
        "parents": [
            "FastForward\\Container\\ServiceProvider\\AggregateServiceProvider"
        ],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 20,
        "loc": 28,
        "lloc": 8,
        "mi": 219.3,
        "mIwoC": 171,
        "commentWeight": 48.3,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "FastForward\\Framework\\ServiceProvider\\",
        "pageRank": 0.58,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "FastForward\\Framework\\Tests\\ServiceProvider\\FrameworkServiceProviderTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "setUp",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFactoriesWillReturnAggregatedServiceProviderFactories",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getExtensionsWillReturnAggregatedServiceProviderExtensions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "PHPUnit\\Framework\\TestCase",
            "FastForward\\Framework\\ServiceProvider\\FrameworkServiceProvider",
            "FastForward\\EventDispatcher\\ServiceProvider\\EventDispatcherServiceProvider",
            "FastForward\\Http\\ServiceProvider\\HttpServiceProvider",
            "FastForward\\Clock\\ServiceProvider\\ClockServiceProvider",
            "FastForward\\Container\\Factory\\ServiceFactory",
            "FastForward\\Clock\\ServiceProvider\\ClockServiceProvider",
            "FastForward\\Container\\Factory\\ServiceFactory",
            "FastForward\\Container\\Factory\\ServiceFactory",
            "FastForward\\Http\\ServiceProvider\\HttpServiceProvider",
            "FastForward\\EventDispatcher\\ServiceProvider\\EventDispatcherServiceProvider",
            "FastForward\\Clock\\ServiceProvider\\ClockServiceProvider"
        ],
        "parents": [
            "PHPUnit\\Framework\\TestCase"
        ],
        "implements": [],
        "lcom": 1,
        "length": 39,
        "vocabulary": 10,
        "volume": 129.56,
        "difficulty": 1.72,
        "effort": 223.12,
        "level": 0.58,
        "bugs": 0.04,
        "time": 12,
        "intelligentContent": 75.23,
        "number_operators": 8,
        "number_operands": 31,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 12,
        "loc": 44,
        "lloc": 32,
        "mi": 88.15,
        "mIwoC": 51.97,
        "commentWeight": 36.18,
        "kanDefect": 0.61,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 121,
        "totalStructuralComplexity": 363,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 363,
        "package": "FastForward\\Framework\\Tests\\ServiceProvider\\",
        "pageRank": 0.42,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    }
]